name: mooBarGraph
author: kopipejst
category: Widgets
tags: [graph, ajax]
docs: http://workshop.rs/2010/02/moobargraph-ajax-graph-for-mootools/
demo: http://workshop.rs/projects/moobargraph
current: 1.0