name: mooBarGraph
author: Ivan Lazarevic
category: Widgets
tags: [graph, ajax]
#docs: http://workshop.rs/2010/02/moobargraph-aj…h-for-mootools/
#demo: http://workshop.rs/projects/moobargraph
#current: 1.0